### ISSUE TITLE
Definição de nova API para integração PGD-SIAPE

### ISSUE THREAD

**Issue by cimei** [gestaogovbr/api-pgd#116]
Em face à possibilidade de termos uma API exclusiva para resgatar dados do SIAPE para o PGD, foi elaborado documento com os requisitos mínimos desejados.

**Comment by cimei** [comment]
Minuta https://docs.google.com/document/d/e/2PACX-1vRQ8CI_ArBnQ9Ms-BSQb33QKUrdziIFO5oN8WIkUfthqUeyGHcTZtPCINZzr3QO8Qvgsiiv3b9g0Ku_/pub compartilhada no chat Teams:  Petrvs-Conecta-WSSIAPE - Alinhamento da Integração.

**Comment by augusto-herrmann** [comment]
@cimei, estou entendendo que isso é uma demanda para criar uma nova API com dados do SIAPE, para ser utilizada pelo Petrvs, certo?

No caso, isso seria um novo projeto, sem vinculação com esta API PGD, de recepção dos dados dos sistemas de PGD, da qual se trata este repositório no Github.
