### ISSUE TITLE
Criar testes para a ferramenta admin_tools

### ISSUE THREAD

**Issue by nitaibezerra** [gestaogovbr/api-pgd#14]
Criar testes unitários para testar as partes (truncar usuário, truncar planos de trabalhos, criar usuários, etc) do admin_tools.

**Comment by augusto-herrmann** [comment]
A ferramenta `admin_tools` será descontinuada a partir da versão `0.2.x`, substituída pela aplicação [Fief](https://docs.fief.dev/), que [tem seus próprios testes](/fief-dev/fief/tree/main/tests).

Reavaliar a necessidade de criar esses testes para a versão legada no branch `0.1.x`.

**Comment by augusto-herrmann** [comment]
Com a implantação em produção da versão `0.2.1`, o _branch_ `0.1.x` não voltará a receber novas funcionalidades.
