### ISSUE TITLE
Alterar o tipo da dado da coluna cod_unidade_exercicio da tabela public.plano_trabalho de integer para bigint

### ISSUE THREAD

**Issue by djangonauta** [gestaogovbr/api-pgd#72]
Olá pessoal. Em nosso instituto os códigos das unidades de exercício podem ser bem longos. Ao simularmos a submissão dos dados dos nossos planos individuais tanto localmente, quando no ambiente de homologação http://hom.api.programadegestao.economia.gov.br/, ocorre um erro devido ao tamanho desse campo.

Quando alteramos o tipo da coluna cod_unidade_exercicio,  a submissão é feita com sucesso:

`api_pgd=# alter table public.plano_trabalho alter cod_unidade_exercicio type bigint;
`

Não conheço SQLAlchemy, mas seria possível uma alteração no campo `cod_unidade_exercicio = Column(Integer)` para `cod_unidade_exercicio = Column(BigInteger)`?

**Comment by edulauer** [comment]
@djangonauta a alteração foi efetuada no código do repositório e no banco de homologação, por favor se puder validar a solução agradeço.

**Comment by djangonauta** [comment]
Todos os quase mil registros foram cadastrados com sucesso no ambiente de homologação. Fiz a verificação na api e aparentemente está tudo ok.

![api](https://github.com/gestaogovbr/api-pgd/assets/2979844/cf4eb77e-9955-4520-a4bf-0d038d26ccb4)

Obrigado!

**Comment by edulauer** [comment]
Ok, iremos providenciar a alteração em produção. Obrigado pela contribuição!
